server:
  port: 8088

spring:
  application:
    name: payment
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin
  datasource:
    url: jdbc:postgresql://localhost:5434/payment
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        show_sql: true
  output:
    ansi:
      enabled: always

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

ecommerce:
  broker:
    exchange:
      orderPaymentCommand: order-payment
      userEvent: ecommerce-userevent
    queue:
      orderPaymentRequest: order-payment-request
      userEvent: payment-user-event
    key:
      bindOrderRequestCommand: order-payment-request
      bindOrderReplyCommand: order-payment-reply


